# (c) Copyright 2022, pr3d4t0r

# vim: set fileencoding=utf-8:


version: '3'

services:
    lucyfer:
        container_name: 'lucyfer'
        environment:
            DEVPI_HOST             : '${DEVPI_HOST}'
            GRANT_SUDO             : 'yes'
            JUPYTER_LAB_ENABLE     : 'yes'
            PIP_TRUSTED_HOST       : '${PIP_TRUSTED_HOST}'
        image: 'pr3d4t0r/lucyfer:latest'
        ports:
            # *****************************************************************
            # Important:  the IP address binding depends on the host's 
            # configuration.  Binding to specific IP addresses on macOS doesn't
            # work, but it works fine under Linux.  This needs to be resolved 
            # throuth a target configuration manager later.  The lo interface
            # works across all operating systems but may open vulnerabililities
            # or affect the firewall configuration under Linux.
            # *****************************************************************
            # - 127.0.0.1:8805:8888
            # For LAN availability:
            - 8805:8888
        privileged: true
        user: 'root:${JUPYTER_LAB_GROUP}'
        volumes:
            - '${LUCYFER_WORKSPACE}:/home/jovyan'

