# (c) Copyright 2022 pr3d4t0r

# vim: set fileencoding=utf-8:


version: '3'

services:
    kallisto_service:
        container_name: 'kallisto'
        environment:
            BLAZEGRAPH_UID: '${BLAZEGRAPH_UID}'
            BLAZEGRAPH_GID: '${BLAZEGRAPH_GID}'
        image: 'lyrasis/blazegraph:2.1.5'
        ports:
            - 8889:8080
        privileged: true
        volumes:
            - '${BLAZEGRAPH_DATA}:/data'

