#!/bin/bash

# (c) Copyright 2022 by the Lucyfer Contributors

# vim: set fileencoding=utf-8:

set -e


# +++ constants +++

LUCYFER_GITHUB_FILES=(
    "README-1ST.ipynb"
    "README-SPARQL.ipynb"
    "README-Kotlin.ipynb"
    "lucy" )
LUCYFER_GITHUB_PATH="https://raw.githubusercontent.com/pr3d4t0r/lucyfer/master"
LUCYFER_HUB_VERSION="2.1.0"


# *** functions ***

die() {
    echo "$1"
    exit "$2"
} # die


assertActionInCLI() {
    local syntax="syntax: lucy env | start | stop | status | update | version"
    [[ -z "$1" ]] && die "Command missing; $syntax" 8

    case "$1" in
        "env")
            ;;
        "start")
            ;;
        "start86")
            ;;
        "stop")
            ;;
        "status")
            ;;
        "update")
            ;;
        "version")
            ;;
        *)
            die "$syntax" 9
            ;;
    esac
} # assertActionInCLI


assertDockerServiceIsRunning() {
    local uname=$(uname)
    local message="Docker daemon not running"

    case "$uname" in
        "Darwin")
            [[ -n $(ps aux | awk '/Docker Desktop\.app/') ]] || die "$message" 4
            ;;
        "Linux")
            die "Linux not supported yet" 6
            ;;
        *)
            die "$uname not supported" 3
    esac
} # assertDockerServiceIsRunning


assertDockerIsAvailable() {
    which docker-compose > /dev/null || die "docker-compose unavailable or not in path" 1
} # assertDockerIsAvailable


assertDockerComposeFileExists() {
    if [[ -z "$LUCYFER_COMPOSE" ]]
    then
        export LUCYFER_COMPOSE='lucyfer-compose.yaml'
    fi
    [[ -e "$LUCYFER_COMPOSE" ]] || die "$LUCYFER_COMPOSE is not present in pwd == $(pwd)" 2
} # assertDockerComposeFileExists


assertWorkspaceExists() {
    if [[ -z "$LUCYFER_WORKSPACE" ]]
    then

cat <<EOF

The LUCYFER_WORKSPACE environment variable must point at the fully qualified
path to the working directory where the user intends to store Jupyter notebooks
and data.  This script links the Jupyter jovyan user $USER to LUCYFER_WORKSPACE
for storing state, data, and notebooks.

From the command line, do:

export LUCYFER_WORKSPACE=/path/to/workspace/dir

Where /path/to/workspace/dir is your workspace.

EOF

        export LUCYFER_WORKSPACE="$(pwd)"
        echo "LUCYFER_WORKSPACE=$LUCYFER_WORKSPACE"
    fi
} # assertWorkspaceExists


assertDataRepositoryExists() {
    if [[ -z "$BLAZEGRAPH_DATA" ]]
    then
cat << EOF

The BLAZEGRAPH_DATA environment variable must point at the fully qualified
path to the working directory where the user intends to store graph data files.
This script links /data in the Blazegraph container to BLAZEGRAPH_DATA for
storing database configuration and data.

From the command line, do:

export BLAZEGRAPH_DATA=/path/to/data/repository

Where /path/to/data/repository is the database work area.

EOF
        export BLAZEGRAPH_DATA="$(pwd)/data"
        echo "BLAZEGRAPH_DATA=$BLAZEGRAPH_DATA"
    fi

    mkdir -p "$BLAZEGRAPH_DATA"
} # assertDataRepositoryExists


setOwnership() {
    # Set ownership to the correct user:group to avoid conflicts
    # between the internal Docker container user names and the 
    # host's.
    #
    # This script resolves to the userID:groupID of the account
    # from whence it was invoked.
    #
    # Documented method because Docker permissions and ownership
    # kinda suck.
    export BLAZEGRAPH_GID=$(id -g)
    export BLAZEGRAPH_UID=$(id -u)
    export JUPYTER_LAB_GID=$(id -g)
    export JUPYTER_LAB_UID=$(id -u)
} # setOwnership


_snuffContainer() {
    [[ -n "$1" ]] || die "container name not specified in _snuffContainer()" 5

    local container=$(docker ps -a | awk -v "containerName=$1" '$0 ~ containerName { print($NF); }')

    if [[ -n "$container" ]]
    then
        docker rm -f "$container"
    fi
} # _snuffContainer


resolveImageByPlatform() {
   local platform=$(uname -a | awk 'BEGIN { m = "ARM64"; i = "X86"; } { if ($14 ~ m) print(m); if ($14 ~ i) print(i); }')

    case "$platform" in
        "ARM64")
            export LUCYFER_IMAGE="pr3d4t0r/lucyfer-m:$LUCYFER_HUB_VERSION"
            ;;
        "X86")
            export LUCYFER_IMAGE="pr3d4t0r/lucyfer:$LUCYFER_HUB_VERSION"
            ;;
        *)
            die "host platform not supported" 7
            ;;
    esac
} # resolveImageByPlatform


showJupyterDatascienceLab() {
    echo ""
    docker-compose -f "$LUCYFER_COMPOSE" ps -a
} # showJupyterDatascienceLab


runJupyterDatascienceLab() {
    _snuffContainer "lucyfer"
    _snuffContainer "kallisto"

    echo ""
    env | awk '/LUCYFER/ || /JUPYTER/ || /HOME/ || /BLAZE/' | sort
    docker-compose -f "$LUCYFER_COMPOSE" up --remove-orphans --no-recreate -d || docker-compose rm -f 
    # TODO: replace with an actual check to see if the container started/is healthy

    sleep 10
    showJupyterDatascienceLab
    docker logs lucyfer 2>&1 | awk -F "?" '/http:/ { gsub("token=", "Lucyfer access token = ", $NF); printf("\n%s\n", $NF); exit(0); }'
} # runJupyterDatascienceLab


killJupyterDatascienceLab() {
    echo ""
    env | awk '/LUCYFER/ || /JUPYTER/ || /HOME/ || /BLAZE/' | sort
    docker-compose -f "$LUCYFER_COMPOSE" stop
    showJupyterDatascienceLab
} # killJupyterDatascienceLab


displayEnvironment() {
    echo "export LUCYFER_WORKSPACE=$(pwd)"
    echo "export BLAZEGRAPH_DATA=$(pwd)/data"
} # displayEnvironment


_fetchFileFrom() {
    local fullURL="$1"
    local targetLocation="$2"
    
    if [[ -n "$(which wget)" ]]
    then
        wget -O "$targetLocation" "$fullURL"
    elif [[ -n "$(which curl)" ]]
    then
        curl -o "$targetLocation" "$fullURL"
    else
        die "Neither wget nor cURL are available; install either and retry" 10
    fi
} # _fetchFileFrom


update() {
    local fileName
    local fullURL
    local localPath

    for fileName in ${LUCYFER_GITHUB_FILES[@]}
    do
        fullURL="$LUCYFER_GITHUB_PATH/$fileName"
        localPath="./$fileName"
        echo ">> $fullURL"
        echo [[ -e "$localPath" ]] && rm -f "$localPath"
        _fetchFileFrom "$fullURL" "$localPath"
        echo ""
    done

    # Heuristic:
    chmod +x "./lucy"

    docker pull "$LUCYFER_IMAGE"

    echo "Lucyfer update complete"
} # update


version() {
    printf "\nLucyfer version: $LUCYFER_HUB_VERSION\n"
} # version


# *** main ***

action="$1"
assertActionInCLI "$action"
assertDockerServiceIsRunning
assertDockerIsAvailable
assertDockerComposeFileExists
assertWorkspaceExists
assertDataRepositoryExists
setOwnership
resolveImageByPlatform

case "$action" in
    "env")
        displayEnvironment
        ;;
    "start")
        runJupyterDatascienceLab
        ;;
    "start86")
        export LUCYFER_IMAGE="pr3d4t0r/lucyfer:$LUCYFER_HUB_VERSION"
        runJupyterDatascienceLab
        ;;
    "status")
        showJupyterDatascienceLab
        ;;
    "stop")
        killJupyterDatascienceLab
        ;;
    "update")
        update
        ;;
    "version")
        version
        ;;
esac
echo ""

