#!/bin/bash

# *** functions ***

function setJupyterWorkspacePermissions {
    chmod 777 ./work

    mkdir -p ./.jupyter
    chmod 775 ./.jupyter
} # setJupyterWorkspacePermissions



# *** main ***

setJupyterWorkspacePermissions

