#!/bin/bash

# (c) Copyright 2022, pr3d4t0r

# vim: set fileencoding=utf-8:


# *** functions ***

die() {
    echo "$1"
    exit "$2"
} # die


assertDockerIsAvailable() {
    which docker-compose > /dev/null || die "docker-compose unavailable or not in path" 1
} # assertDockerIsAvailable


assertDockerComposeFileExists() {
    [[ -e "./docker-compose.yaml" ]] || die "docker-compose.yaml is not present in pwd == $(pwd)" 2
} # assertDockerComposeFileExists


assertWorkspaceExists() {
    if [[ -z "$LUCYFER_WORKSPACE" ]]
    then

cat <<EOF
The LUCYFER_WORKSPACE environment variable must point at the fully qualified
path to the working directory where the user intends to store Jupyter notebooks
and data.  This script links the Jupyter jovyan user $HOME to $LUCYFER_WORKSPACE
for storing state, data, and notebooks.

From the command line, do:

export LUCYFER_WORKSPACE=/path/to/workspace/dir

Where /path/to/workspace/dir is your workspace.

EOF

        die "Please orrect this issue and try again" 3
    fi
} # assertWorkspaceExists


setOwnership() {
    # Set ownership to the correct user:group to avoid conflicts
    # between the internal Docker container user names and the 
    # host's.
    #
    # This script resolves to the userID:groupID of the account
    # from whence it was invoked.
    #
    # Documented method because Docker permissions and ownership
    # kinda suck.
    export JUPYTER_LAB_USER=$(id -u)
    export JUPYTER_LAB_GROUP=$(id -g)
} # setOwnership


runJupyterScienceLab() {
    local lucyferContainer=$(docker ps | awk '$0 ~ "lucyfer" { print($NF); }')

    if [[ -n "$lucyferContainer" ]]
    then
        docker rm -f "$lucyferContainer"
    fi

   env | awk '/JUPYTER/ || /HOME/' | sort
   docker-compose up --remove-orphans --no-recreate -d || docker-compose rm -f 
} # runJupyterScienceLab


# *** main ***

assertDockerIsAvailable
assertDockerComposeFileExists
assertWorkspaceExists
setOwnership
runJupyterScienceLab

