# (c) Copyright 2022 Lucyfer Contributors

# vim: set fileencoding=utf-8:


# TODO:  Implement buildx in a safe manner
# docker buildx use lucyfer-builder
# FROM            jupyter/scipy-notebook:latest
FROM            --platform=linux/amd64 jupyter/scipy-notebook:latest
MAINTAINER      lucyfer AT cime.net


USER            root


